import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./(components)/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gray-50">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen text-gray-900`}
      >
        <div className="md:pl-64">
          <Sidebar />
          <div className="pb-24">{children}</div>
        </div>
        <div className="md:hidden">
          {/* Mobile bottom nav */}
          {/* @ts-expect-error Server Components cannot auto-detect client components here; dynamic import preferred later */}
          {(await import("./(components)/BottomNav")).BottomNav()}
        </div>
      </body>
    </html>
  );
}
